target-version = "py39"
line-length = 120

[lint]
# E4/E7/E9: syntax, F: pyflakes, I: isort, B: bugbear, UP: pyupgrade
select = ["E4", "E7", "E9", "F", "I", "B", "UP"]
ignore = [
  "E501",
]

[format]
quote-style = "preserve"
indent-style = "space"

[lint.per-file-ignores]
"main.py" = ["F403", "F405"]
"web_server.py" = ["B008"]
